#!/usr/bin/env python3
"""Regenerate THIRD_PARTY_NOTICES.txt from what actually ships.

The Windows executable bundles the Python runtime dependency tree and the built
SPA, and the Tauri installer redistributes that executable. Several of those
licences require the notice to travel with the binary — MIT and BSD ask for the
copyright line, and **MPL-2.0 (certifi) additionally requires telling recipients
how to obtain the source of that file**. Without a notices file the redistributed
build cannot satisfy those terms.

This is a build/dev tool, not a runtime dependency: it reads installed metadata
that is already present and adds nothing to the shipped tree.

Usage
-----
    uv run python scripts/gen_third_party_notices.py            # write the file
    uv run python scripts/gen_third_party_notices.py --check    # CI: fail if stale

The frontend half is produced by ``npx license-checker`` and passed in with
``--frontend <json>``; when it is absent the existing frontend section is kept so
that running this without Node does not silently delete it.
"""

from __future__ import annotations

import argparse
import importlib.metadata as metadata
import json
import sys
from pathlib import Path

OUT = Path("THIRD_PARTY_NOTICES.txt")
FRONTEND_MARKER = "## Frontend (npm)"

HEADER = """VisualizeBetter — third-party notices
=====================================

VisualizeBetter is distributed under the MIT licence (see LICENSE). The
redistributable builds — the PyInstaller executable and the Tauri installer that
carries it — also contain the third-party components listed below, each under its
own licence.

This file is generated by scripts/gen_third_party_notices.py; edit that, not this.

Source obligations
------------------

certifi is licensed under the Mozilla Public License 2.0. MPL-2.0 section 3.2
requires that recipients of a binary be told how to obtain the source form of the
covered file. The source for the exact version bundled here is available at:

    https://pypi.org/project/certifi/#files
    https://github.com/certifi/python-certifi

dompurify is offered under "MPL-2.0 OR Apache-2.0". This distribution elects
Apache-2.0, so no MPL source-availability obligation attaches to it.

google-re2 wraps RE2 and Abseil (both BSD-3-Clause); their sources are at
https://github.com/google/re2 and https://github.com/abseil/abseil-cpp.

The Windows builds also vendor the Microsoft Visual C++ runtime redistributable
DLLs (msvcp140*.dll) via delvewheel, redistributable under the Microsoft Visual
C++ Redistributable terms.

"""


def python_rows() -> list[tuple[str, str, str]]:
    rows: dict[str, tuple[str, str, str]] = {}
    for dist in metadata.distributions():
        name = dist.metadata["Name"]
        if not name or name.lower() == "visualizebetter":
            continue
        licence = (dist.metadata.get("License-Expression") or "").strip()
        if not licence:
            raw = (dist.metadata.get("License") or "").strip().splitlines()
            licence = raw[0] if raw else ""
        if not licence or len(licence) > 60:
            classifiers = [
                c for c in (dist.metadata.get_all("Classifier") or [])
                if c.startswith("License ::")
            ]
            licence = classifiers[0].split("::")[-1].strip() if classifiers else "see project"
        rows[name.lower()] = (name, dist.version or "", licence)
    return [rows[key] for key in sorted(rows)]


def frontend_rows(path: Path | None) -> list[tuple[str, str, str]]:
    if path is None or not path.exists():
        return []
    data = json.loads(path.read_text(encoding="utf-8"))
    rows = []
    for spec, info in sorted(data.items()):
        name, _, version = spec.rpartition("@")
        if name in ("frontend", "visualizebetter"):
            continue  # our own package, not a third party
        licence = info.get("licenses")
        if isinstance(licence, list):
            licence = " OR ".join(licence)
        rows.append((name or spec, version, str(licence or "see package")))
    return rows


def table(rows: list[tuple[str, str, str]]) -> str:
    if not rows:
        return "    (not regenerated on this run — see the script's --frontend flag)\n"
    width = max(len(r[0]) for r in rows)
    return "".join(f"    {n:<{width}}  {v:<16}  {lic}\n" for n, v, lic in rows)


def render(front: list[tuple[str, str, str]], keep_frontend: str | None) -> str:
    body = HEADER + "## Python\n\n" + table(python_rows()) + "\n" + FRONTEND_MARKER + "\n\n"
    if front:
        return body + table(front)
    return body + (keep_frontend or table([]))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--frontend", type=Path, default=None,
                        help="JSON from `npx license-checker --json`")
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the file on disk is out of date")
    args = parser.parse_args()

    previous = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
    kept = previous.split(FRONTEND_MARKER, 1)[1].lstrip("\n") if FRONTEND_MARKER in previous else None
    text = render(frontend_rows(args.frontend), kept)

    if args.check:
        if previous != text:
            print(f"{OUT} is out of date — run scripts/gen_third_party_notices.py", file=sys.stderr)
            raise SystemExit(1)
        print(f"{OUT} is up to date")
        return

    OUT.write_text(text, encoding="utf-8")
    print(f"{OUT}: {len(python_rows())} Python packages, {len(frontend_rows(args.frontend))} npm packages")


if __name__ == "__main__":
    main()
