/**
 * [9-D] render_in_chat card — real-browser standalone render + [11] XSS safety.
 *
 * The card HTML is generated by the Python side (server-embedded snapshot), so we
 * generate it here through the same code path and load it with setContent (no serve
 * — the card is self-contained). Confirms the subgraph draws (SVG) and that a
 * hostile, AI-sourced label is inert (rendered as text, never executed).
 */

import { execFileSync } from 'node:child_process'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { expect, test } from '@playwright/test'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const REPO = path.resolve(HERE, '..', '..')
const PYTHON =
  process.platform === 'win32'
    ? path.join(REPO, '.venv', 'Scripts', 'python.exe')
    : path.join(REPO, '.venv', 'bin', 'python')

function card(subgraph: unknown): string {
  // JSON via stdin, not argv — avoids Windows command-line escaping of the
  // hostile label's quotes/angle brackets.
  const script =
    'import json,sys;sys.stdout.reconfigure(encoding="utf-8");' +
    'from visualizebetter.render_in_chat import render_card_html;' +
    'sys.stdout.write(render_card_html(json.loads(sys.stdin.read())))'
  return execFileSync(PYTHON, ['-c', script], {
    cwd: REPO,
    input: JSON.stringify(subgraph),
    encoding: 'utf8',
  })
}

const NORMAL = {
  root: { id: 'A', label: 'Alpha', type: 'class' },
  neighbors: [
    { id: 'B', label: 'Beta', type: 'service' },
    { id: 'C', label: 'Gamma', type: 'module' },
  ],
  edges: [
    { source: 'A', target: 'B', relation: 'calls' },
    { source: 'A', target: 'C', relation: 'ref' },
  ],
}

const HOSTILE = {
  root: { id: 'A', label: 'Alpha', type: 'class' },
  neighbors: [
    { id: 'X', label: '</script><img src=x onerror="window.__pwned=true">', type: 'class' },
  ],
  edges: [{ source: 'A', target: 'X', relation: 'ref' }],
}

const normalCard = card(NORMAL)
const hostileCard = card(HOSTILE)

test('renders the subgraph standalone (SVG nodes, labels, edges)', async ({ page }) => {
  await page.setContent(normalCard)
  await expect(page.locator('svg circle')).toHaveCount(3) // root + 2 neighbors
  await expect(page.locator('svg line')).toHaveCount(2) // 2 edges
  await expect(page.locator('svg text')).toContainText(['Alpha'])
})

test('★ a hostile label is inert — text, never executed (XSS)', async ({ page }) => {
  let dialog = false
  page.on('dialog', (d) => {
    dialog = true
    void d.dismiss()
  })
  await page.setContent(hostileCard)

  // The onerror never runs — the label became SVG <text>, not an <img>.
  expect(await page.evaluate(() => (window as unknown as { __pwned?: boolean }).__pwned)).toBeFalsy()
  expect(dialog).toBe(false)
  expect(await page.locator('img').count()).toBe(0)
  // ...and the raw text is present, escaped, inside the SVG label.
  await expect(page.locator('svg text')).toContainText(['</script>'])
})

test('declares a strict no-external CSP', async ({ page }) => {
  await page.setContent(normalCard)
  const csp = await page
    .locator('meta[http-equiv="Content-Security-Policy"]')
    .getAttribute('content')
  expect(csp).toContain("default-src 'none'")
  expect(csp).toContain("connect-src 'none'")
})
